### ISSUE TITLE
Update SolveSpace build

### ISSUE THREAD

**Issue by Symbian9** [AlexanderP/html#2]
Так как с недавних пор активная разработка SolveSpace возобновилась, очень хотелось бы иметь более частые свежые сборки для тестирования :-)

Пожалуйста, обнови сборку с багфиксами за 31 июля:

- https://github.com/solvespace/solvespace/commits/master

Также, твой PPA репозитарий добавили в список известных источников бинарных пакетов в `README.md` ;-)

- https://github.com/solvespace/solvespace/commit/88d59ea7658db15bfd0adb9dd38802f574ac7f9b
- https://github.com/solvespace/solvespace/blob/master/README.md

**Comment by AlexanderP** [comment]
Я буду стараться делать по чаще. Но сам понимаешь время, оно такое. 
Последний коммит собрал. 
Да, это здорово но зачем они сослались на пакет с исходника?

**Comment by Symbian9** [comment]
> Я буду стараться делать по чаще. Но сам понимаешь время, оно такое.

Конечно, понимаю ;-) Самому времени тоже нехватает на всё задуманое...

> Последний коммит собрал.

СПАСИБО! Щас буду тестить :-)

> Да, это здорово но зачем они сослались на пакет с исходника?

А ты можешь сделать так чтобы на страницах исходников были ссылки на страници с бинарными пакетами?

**Comment by AlexanderP** [comment]
> А ты можешь сделать так чтобы на страницах исходников были ссылки на страници с бинарными пакетами?

Да, надо немного скрипт переписать, но опять же у многих исходников куча пакетов...как с ними быть надо подумать)

**Comment by Symbian9** [comment]
В SolveSpace добавили пару коммитов с исправлениями, если будет время, пересобери пакеты, пожалуйста ;-)

**Comment by AlexanderP** [comment]
Вчера обновил

**Comment by Symbian9** [comment]
В SolveSpace исправили несколько багов. Пожалуйста, обнови deb'ы.

P.S.: Можешь выложить скрипты которые ты используешь для компиляции SolveSpace и сборки deb'ов?

**Comment by AlexanderP** [comment]
Привет) обновил.

Я хочу их выложить, но сначала я до ума их доведу)

вс, 17 февр. 2019 г., 11:13 app4soft notifications@github.com:

**Comment by Symbian9** [comment]
В новой сборке (`solvespace_3.0.0~git1294-9d1601e-1_amd64.deb`) в меню "Help > About" отображается версия git НЕ соответствующая указанной в названии DEB-пакета.

> This is SolveSpace version 3.0~83a0a517

**Comment by AlexanderP** [comment]
В файле: `https://github.com/solvespace/solvespace/blob/master/CMakeLists.txt`

> **Развёртывание ключа**
> Разработчики, привыкшие к SVN или CVS, часто хотят получить в Git'е возможность развёртывания ключа в стиле этих систем. Основная проблема с реализацией этой функциональности в Git'е это то, что нельзя записать в файл информацию о коммите после того, как коммит был сделан, так как Git сначала считает контрольную сумму для файла. Несмотря на это, вы можете вставлять текст в файл во время его выгрузки и удалять его перед добавлением в коммит. Атрибуты Git'а предлагают два варианта сделать это.
> 
> Во-первых, вы можете внедрять SHA-1-сумму блоба в поле `$Id$` в файл автоматически. Если установить соответствующий атрибут для одного или нескольких файлов, то в следующий раз, когда вы будете выгружать данные из этой ветки, Git будет заменять это поле SHA-суммой блоба. **Обратите внимание, что это SHA-1 не коммита, а самого блоба.**

https://git-scm.com/book/ru/v1/Настройка-Git-Git-атрибуты#Развёртывание-ключ

Как я понял это разные значения) и они не будут равны...

**Comment by Symbian9** [comment]
В SolveSpace добавили несколько коммитов ;-)

**Comment by Symbian9** [comment]
SolveSpace обновился ;-)

P.S.: @AlexanderP у меня к тебе просьба: можешь скомпилить для меня *AzPainter v2.1.4* в ближайшие пару дней для Debian 9 (amd64) и выложить DEB на transfer.sh? (но НЕ обновляй пока сборки на своём сайте!)

- http://osdn.dl.osdn.jp/azpainter/71501/azpainter-2.1.4.tar.xz

Мы сейчас работаем над переводом для 2.1.4, и думаю на следующей неделе уже можно будет опакечивать

- https://github.com/Symbian9/azpainter/issues/58

Я пока не мержил оригинальный код в сврю репу

**Comment by AlexanderP** [comment]
Привет. Не вижу смысла внепланово песобирать SolveSpace, так как версия 3.0.0~git1302-fa66229 уже в репе. Последний комит решил проблему с отображением ревизии в программе. О чем мы говорили выше, но для stretch я его собрал. Так же собрал azpainter)

https://transfer.sh/xMehr/deb-result.7z

**Comment by Symbian9** [comment]
Вчера в SolveSpace добавили инструмент для создания резьб/спиралей (helical group) - если будет время, пересобери пакет, пожалуйста!

P.S.: Спасибо зв обновку AzPainter `2.1.4-2` ;-)

**Comment by Symbian9** [comment]
В SolveSpace завезли новых коммитов, хотелось бы и свежих ночнушек. 😎

А тем временем, тут [по случаю](https://twitter.com/app4soft/status/1166547477245374464), прорекламировал твой Патреон ([раз](https://github.com/Symbian9/SolveSpace-Daily-Engineering); [два](https://twitter.com/app4soft/status/1167570478501941250); [три](https://www.linux.org.ru/gallery/screenshots/15193919)) 😉

**Comment by AlexanderP** [comment]
Спасибо. Я вчера как раз  вечером его обновил)

сб, 31 авг. 2019 г. в 03:58, app4soft <notifications@github.com>:

**Comment by AlexanderP** [comment]
Готово ;)

чт, 12 сент. 2019 г. в 22:00, app4soft <notifications@github.com>:

**Comment by Symbian9** [comment]
У меня тут вопросик возник: для винды есть и стандартная и CLI-версия
 
- https://ci.appveyor.com/project/whitequark/solvespace/build/artifacts

А почему нет `solvespace-cli` в твоих пакетах? Можешь добавить сборку `solvespace-cli` и запихивать внутрь пакета `solvespace_3.0.0~git{build_ID}-{commit_ID}_amd64.deb`?

**Comment by AlexanderP** [comment]
Есть ли смысл делать ее отдельным пакетом?

**Comment by Symbian9** [comment]
> Есть ли смысл делать ее отдельным пакетом?

Думаю, нет. достаточно воткнуть бинарник `solvespace-cli` в основной пакет `solvespace`.

**Comment by Symbian9** [comment]
Прилетел важный коммит, стоит обновить пакеты

- https://github.com/solvespace/solvespace/commit/

**Comment by AlexanderP** [comment]
Обновлено)

**Comment by Symbian9** [comment]
Спасиб!

Но не успел толком потестить как новая пачка коммитов прилетела - https://github.com/solvespace/solvespace/commits/master

P.S.: Может стоит сделать на базе Travis CI регулярные ночные сборки? (с проверкой были-ли коммиты за день, и если да - то обновлять пакеты в автоматическом режиме)

- https://github.com/solvespace/solvespace/blob/master/.travis.yml

**Comment by AlexanderP** [comment]
Я думал об этом. Он собирает под одну систему. А я его собираю под 8 систем и 2 архитектуры. Как это реализовать в травис ума не приложу... плюс надо подумать с выгрузкой. 

На выходных обновлю)

**Comment by Symbian9** [comment]
> Как это реализовать в травис ума не приложу...

В Travis это делается через `matrix` со списком дистров (или ОС); например, вот как работает сборка *LeoCAD* для Linux, Mac и Windows с последующей выгрузкой на GitHub

- https://github.com/leozide/leocad/blob/master/.travis.yml

**Comment by Symbian9** [comment]
В Travis также можно использовать не только `matrix`, но и `jobs`

- https://github.com/solvespace/solvespace/blob/master/.travis.yml

**Comment by AlexanderP** [comment]
Спасибо и тебя с праздником!

Я делал для kvirc загрузку в ppa для сборки) Примерно год работало...сейчас нет, нет ответа от сервера ppa))

Спасибо. я подумаю как это можно сделать) 
Что бы охватить все системы мне приходит на ум только pbulder в docker. Но здесь я скорее всего упрусь во время выполнения, травис прибивает задачу вроде через час после запуска.

**Comment by Symbian9** [comment]
> травис прибивает задачу вроде через час после запуска.

Ну если FreeCAD успевает скомпилится за это время, то разве сборка SolveSpace занимает больше времени?

- https://github.com/FreeCAD/FreeCAD-AppImage/blob/master/.travis.yml

**Comment by AlexanderP** [comment]
FreeCAD это отдельная тема. Дольше него у меня ни чего не собирается.
Нет, просто думал запустить сборку в одном задании. Без matrix.
Я мог создать это и на своем компе...но здесь я упираюсь в производительность железа.

P.S. за одно azpainter собрал

**Comment by Symbian9** [comment]
> Я мог создать это и на своем компе...

Зачем гробить свой ПК если можно использовать ресурс серверов Travis? :D

Да и хотелось бы уже прикрутить сборку ночнушек к официальной репе и выгрузку на GitHub

- https://github.com/solvespace/solvespace/blob/master/.travis.yml
- https://github.com/probonopd/uploadtool

> за одно azpainter собрал

`2.1.5`? Сгодится для тестов новых локалей, но они пока в работе, так что после окончания перевода кастону для обновления сборки уже с патчами! ;)

SolveSpace пока не обновлял? Вчера в *SolveSpace* `3.0~690f87c` баг нашел в экспорте текста комментов и размеров в PDF

- https://bit.ly/2r6EIIu

**Comment by Symbian9** [comment]
> Нет, просто думал запустить сборку в одном задании. Без matrix.

Можно же подготовить Docker со всеми необходимыми приблудами и запускать как одно задание на Travis.

**Comment by Symbian9** [comment]
Кстати, заметил что в *SolveSpace* `3.0~690f87c` производительность отрисовки значительно возросла — теперь показывает на старте FPS в районе 200-300 (иногда и за 400 зашкаливает)

![pic.1](https://i.imgur.com/NZGOdiR.png)

Ранее FPS у меня выше 60 редко подскакивал.

**Comment by AlexanderP** [comment]
> SolveSpace пока не обновлял? Вчера в SolveSpace 3.0~690f87c баг нашел в экспорте текста комментов и размеров в PDF
Обновил, только под stretch и bionic он сейчас не собирается...cmake требует версии 3.11. Думаю, постараюсь собрать его для сборок.

Насчет трависа буду думать как сделать.

**Comment by AlexanderP** [comment]
> Кстати, заметил что в _SolveSpace_ `3.0~690f87c` производительность отрисовки значительно возросла — теперь показывает на старте FPS в районе 200-300 (иногда и за 400 зашкаливает)
> 
> ![pic.1](https://camo.githubusercontent.com/1dd3e6d65ccf214f1366e42aa5ea9c5dc4353e34/68747470733a2f2f692e696d6775722e636f6d2f4e5a474f6469522e706e67)
> 
> Ранее FPS у меня выше 60 редко подскакивал.

Интересно пойдет ли solvespace для строительного черчения)

**Comment by Symbian9** [comment]
> cmake требует версии 3.11

Зарепортил в багтрекер.

> Интересно пойдет ли solvespace для строительного черчения)

А почему нет?! ;)

- https://twitter.com/Evl_Spirit/status/1139390108241543171

> Drawing houses in reality isn't the same thing as drawing in SolveSpace ;)
>
> ![pic.1](https://pbs.twimg.com/media/D8_tJpDUwAER5qf.jpg)
>
> ![pic.2](https://pbs.twimg.com/media/D8_tKmbUcAAP4Lx.jpg)

Вот только с подгонкой стилей SolveSpace под требования ГОСТ могут возникнуть трудности.

P.S.: У меня в TODO есть проект по созданию рамок под ГОСТ для SolveSpace

**Comment by Symbian9** [comment]
Сегодня whitequark пофиксил `master` понизив CMake до 3.7.2 для сборки под Debian stretch, при этом он сказал что можно собрать и с CMake 3.2 — значит-ли это что текущий SolveSpace `master` всё ещё можно собрать и в Ubuntu Xenial? (там CMake 3.5.1)

**Comment by Symbian9** [comment]
Ну что, поличилось собрать под Debian stretch?

**Comment by AlexanderP** [comment]
> Сегодня whitequark пофиксил `master` понизив CMake до 3.7.2 для сборки под Debian stretch, при этом он сказал что можно собрать и с CMake 3.2 — значит-ли это что текущий SolveSpace `master` всё ещё можно собрать и в Ubuntu Xenial? (там CMake 3.5.1)

> Ну что, поличилось собрать под Debian stretch?

Да, получилось и для xenial и stretch

**Comment by AlexanderP** [comment]
Залил пакеты:

https://transfer.sh/Jhi27/solve.tar.gz

**Comment by Symbian9** [comment]
> Да, получилось и для Xenial

Дополнительно патчил скрипт под  CMake 3.5.1?

Может и под Trusty соберется с пропатченым CMake 3.2.2?

- https://askubuntu.com/questions/610291/how-to-install-cmake-3-2-on-ubuntu
- https://launchpad.net/~george-edison55/+archive/ubuntu/cmake-3.x

Или там намного больше нерешаемых зависимостей?

**Comment by AlexanderP** [comment]
Да там значительно больше зависимостей. Например gcc.

**Comment by Symbian9** [comment]
> Да там значительно больше зависимостей.

Когда-то хотел настроить автосборку AppImage на базе Trusty, но в таком случае возьму за базу Xenial (там нужен какой-то дополнительный патч для `master` под Xenial?)

- https://github.com/Symbian9/solvespace-appimage/blob/master/.travis.yml

FTR, В багтрекере SolveSpace давно висит хотелка по этому поводу, но там досих пор какие-то траблы

- https://bit.ly/2DM68X0

> Интересно пойдет ли SolveSpace для строительного черчения)

А дай-ка пример (картинку или PDF) строительного чертежа? Хочу посмотреть что можно будет сделать в SolveSpace.

**Comment by AlexanderP** [comment]
> > Да там значительно больше зависимостей.
> 
> Когда-то хотел настроить автосборку AppImage на базе Trusty, но в таком случае возьму за базу Xenial (там нужен какой-то дополнительный патч для `master` под Xenial?)
> 
> * https://github.com/Symbian9/solvespace-appimage/blob/master/.travis.yml
> 
> FTR, В багтрекере SolveSpace давно висит хотелка по этому поводу, но там досих пор какие-то траблы

Да нет))
```
--- solvespace-3.0.0~git1447-0b786e6.orig/CMakeLists.txt
+++ solvespace-3.0.0~git1447-0b786e6/CMakeLists.txt
@@ -7,7 +7,7 @@ if(CMAKE_SOURCE_DIR STREQUAL CMAKE_BINAR
             "    mkdir build && cd build && cmake ..")
 endif()
 
-cmake_minimum_required(VERSION 3.7.2 FATAL_ERROR)
+cmake_minimum_required(VERSION 3.5.1 FATAL_ERROR)
 if(NOT CMAKE_VERSION VERSION_LESS 3.11.0)
     cmake_policy(VERSION 3.11.0)
 endif()
```

**Comment by AlexanderP** [comment]
> > Интересно пойдет ли SolveSpace для строительного черчения)
> 
> А дай-ка пример (картинку или PDF) строительного чертежа? Хочу посмотреть что можно будет сделать в SolveSpace.

Мне надо поискать в файлах и я скину что-нибудь

**Comment by Symbian9** [comment]
> Мне надо поискать в файлах и я скину что-нибудь

Есть что?

P.S. Спасибо за свежую сборку SolveSpace! Обновился сегодня ;)

- https://i.imgur.com/EWGH5dI.png

**Comment by AlexanderP** [comment]
Привет. Нужен pdf или dwg?

**Comment by Symbian9** [comment]
> pdf или dwg?

Лучше PDF

**Comment by Symbian9** [comment]
Вчера в *SolveSpace* завезли пару значительних багфиксов и немного добавили зависимостей для сборки.

Если будет такая возможность то обнови пораньше пакеты (с коммитами уже после `211ae8c-1`).

Кстати, может выложиш и свои скрипты для Debian в отдельный реп на GitHub? Хочу прикрутить к Travis для автосборки ночнушек для тестирования ;)

**Comment by AlexanderP** [comment]
Привет.
Только сейчас руки дошли) завал...
https://yadi.sk/d/s3p-jwBL79sQBw
пока так, думаю на неделе реп обновлю)

Насчет скрипта, я его собираюсь переписывать...
В каком виде нужна сборка под все платформы либо под одну?

**Comment by Symbian9** [comment]
> Только сейчас руки дошли) завал...

Да в принципе и вовремя, потому как только вчера добавили в `master` еще одну мою хотелку ("flat colors render mode"), так что всё ОК ;)

> https://yadi.sk/d/s3p-jwBL79sQBw

А можешь на что-то НЕ из Яндекс/MailRu? Может на http://0x0.st/ или https://transfer.sh 

> В каком виде нужна сборка под все платформы либо под одну?

Мне достаточно было бы для Debian `10`

**Comment by AlexanderP** [comment]
https://transfer.sh/ljDbs/solvespace.zip

> Мне достаточно было бы для Debian 10

подумаю как можно сделать )

**Comment by Symbian9** [comment]
@AlexanderP, в последней сборке на основе `222c80e` есть критический баг! Регрессию пофиксили следующим коммитом:

- https://github.com/solvespace/solvespace/commit/3e3ccdca8d6c66080078c46c274cbde645f43cf4

Обнови, пожалуйста, использую самый актуальный `master` (на данный момент - `bd41485`)

**Comment by AlexanderP** [comment]
Обновил

**Comment by Symbian9** [comment]
> Обновил

Спасибо! ;)

P.S. Новая функция в меню "View > ✅ Dim Solid for Sketch Groups" позволяет создавать скетчи (в 2D и в 3D) с вожможностью отображения разноцветных предыдущих твердотельных груп как есть (а не в едином стиле `s00d-#def-dim-solid`):

- https://twitter.com/app4soft/status/1348108114596397056

Пример нанесения на твердотельную модель размеров в 3D:

-  https://youtu.be/KY95-xrbSNo (это видео создавал перед тем как добавили новую функцю)
- SLVS - https://github.com/Symbian9/SolveSpace-Daily-Engineering/tree/master/30DayCADChallenge

**Comment by Symbian9** [comment]
@AlexanderP, если будет возможность обнови DEB — там завезли *"New Group > Link / Assemble... > STL triangle mesh (.stl)"*

- https://github.com/solvespace/solvespace/commit/f6bb0a2d35ba6c67a72170413207d0f28bac216d

**Comment by AlexanderP** [comment]
Привет)
https://transfer.sh/1eE1iSv/solve.tar.gz

**Comment by Symbian9** [comment]
> https://transfer.sh/1eE1iSv/solve.tar.gz

Спасибо! Там на почту кину пример SLVS сборки ;)

**Comment by Symbian9** [comment]
В SolveSpace https://github.com/solvespace/solvespace/commit/2450010bbfa20a1ffbf5fd90b85c4b941f56cb16 (и ранее) есть критический баг со вводом некоторых символов в текстовые поля — обнови DEB до https://github.com/solvespace/solvespace/commit/e07b082eb810d2088c92b97d04e864a4ab95816f, пожалуйста)

- https://twitter.com/SolveSpace/status/1473325397026689028

А еще на днях Azel релизнула AzPainter 3.0.4 и кучу своих других утилит:

- AzPainter `3.0.4` - https://gitlab.com/azelpg/azpainter/-/tags/v3.0.4
- mlk style editor `1.0.4` (редактор тем для AzPainter) - https://gitlab.com/azelpg/mlkstyle/-/tags/v1.0.1
- azfontviewer `1.0.2` (просмотрщик шрифтов) - https://gitlab.com/azelpg/azpainter/-/tags/v3.0.4
- aobook `2.0.2` - https://gitlab.com/azelpg/aobook/-/tags/v2.0.2
- azcomicv `2.0.3` - https://gitlab.com/azelpg/azcomicv/-/tags/v2.0.3
- vasviewer `1.0.1 - https://gitlab.com/azelpg/vasviewer/-/tags/v1.0.1

В AzPainter 3.0.3 был баг с `configure`, но в `3.0.4` уже починили)

- https://twitter.com/SenlinOS/status/1471671606443270145

**Comment by AlexanderP** [comment]
Привет. Добавил на сайт.
Описание и ppa обновлю завтра

**Comment by Symbian9** [comment]
> Описание и ppa обновлю завтра

Там в SolveSpace `master` добавили еще важних коммитов после `5315a69` связаных с повышением производительности:

- https://github.com/solvespace/solvespace/compare/5315a69...985e4fb

Если будет время на выходних, обнови пакет.

Кстати, а как насчет скрипта для сборки DEB с помощью GitHub Actions? Чтобы можна было прикрутить к репе на GitHub и не дергать тебя каждый раз за ночнушками? ;)

**Comment by AlexanderP** [comment]
Привет, пока только так
https://transfer.sh/vUqorB/solvespace.tar.gz

Мои скрипты не подойдут, так как они специфичны. 
Если собирать через docker пакеты будут только под операционную систему используемою в докере) если так устроит скинь пример, какого нибудь Actions? что нибудь подумаю

**Comment by Symbian9** [comment]
> Привет, пока только так
> https://transfer.sh/vUqorB/solvespace.tar.gz

UPD: Спасибо, только **НЕ заливай ету сборку в PPA** — походу там регресия была и коммиты частично откатили!

- https://github.com/solvespace/solvespace/pull/1183

Надо наново пересобирать уже с `5efc148` или что там будет в `master` на момент прочтения етого коммента.

> скинь пример, какого нибудь Actions? что нибудь подумаю

Хорошо, где-то были примери. Поищу и кину линки уже с понедельника.

**Comment by AlexanderP** [comment]
Обновил.
https://notesalexp.org/packages/en/debian/buster/amd64/solvespace/
