### ISSUE TITLE
3.Fetch and install the GnuPG key

### ISSUE THREAD

**Issue by krab** [AlexanderP/html#5]
https://github.com/AlexanderP/html/blob/ee5024af25dc3a35669a7ff1e51b2d74500b4792/html/index.html#L57

https://i.imgur.com/Mu3AVW9.png

Выглядит фигово, вместо трех отдельных команд - одна большая (в итогне не рабочая).

**Comment by AlexanderP** [comment]
Гм обновил пеликан)) Спасибо, сегодня подправлю!

ср, 30 дек. 2020 г., 14:14 Alexey Ivanov <notifications@github.com>:
